### ISSUE TITLE
Spyder and makpass.advpass()

### ISSUE THREAD

**Issue by PominausGH** [FuturisticGoo/maskpass#2]
When I run code in spyder pwd = maskpass.advpass() the console will hang and not run anymore code.
![image](https://user-images.githubusercontent.com/89509128/195478283-14df3c86-dce9-4cce-93e7-ca4ad20bc75c.png)
10 mins after running

**Comment by FuturisticGoo** [comment]
Can you tell me your OS and Python version please?

**Comment by PominausGH** [comment]
win10 and 3.9.12

**Comment by PominausGH** [comment]
Spyder IDE

**Comment by FuturisticGoo** [comment]
Can you check if the newest commit works? I haven't yet pushed it to pypi.org so you'll have to install it using <br/> `pip install https://github.com/FuturisticGoo/maskpass/archive/refs/heads/main.zip`

**Comment by PominausGH** [comment]
Hey Mate, thanks for the help I installed the link but I it still hangs as soon as I press enter

**Comment by PominausGH** [comment]
Hey I reinstalled Spyder and now it works

**Comment by PominausGH** [comment]
Thank you so much
