### ISSUE TITLE
Can't install maskpass from Pycharm or compile the package in general

### ISSUE THREAD

**Issue by ZSHUser01** [FuturisticGoo/maskpass#5]
Hi, 

I'm writing to you because i would like to know if you know a possible solution for this problem as I'm planning to use your library in a project of mine. 

Thank you for what you're doing.

Have a nice day

PS: I'll leave the output that Pycharm gives me when trying to install your library as a text file attached to this message
[pycharm-output.txt](https://github.com/FuturisticGoo/maskpass/files/10217228/pycharm-output.txt)

**Comment by FuturisticGoo** [comment]
Terribly sorry about the late response. This looks like the same issue as this [new one](https://github.com/FuturisticGoo/maskpass/issues/7). That is, you'll have to install the python development packages.  
I don't know what linux distro you're using so if you have any doubts regarding the installation, you can ask here.

**Comment by FuturisticGoo** [comment]
I'm gonna close this for now since it looks like the same issue. Feel free to reopen if needed.
